group: travis_latest
dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
language: python
python: 3.7

install:
 - pip install flake8
 - pip install -r requirements.txt

before_script:
 # Static analysis
 - flake8 --statistics --show-source --count .

script:
 - travis_wait 65 time python3 -m py_versions_and_distros

matrix:
 fast_finish: true
