language: python

python:
 - 3.6

sudo: false

install:
 - pip install flake8
 - pip install -r requirements.txt

script:
 # Static analysis
 - flake8 --statistics --count .

matrix:
  fast_finish: true
